bases:
- "{{ requiredEnv "MYDIR" }}/helmfile/envs.yaml"
---
repositories:
# deprecated
- name: stable
  url: "https://charts.helm.sh/stable"
- name: incubator
  url: "https://charts.helm.sh/incubator"

- name: jetstack  # https://github.com/jetstack/cert-manager/tree/master/deploy/charts/cert-manager
  url: "https://charts.jetstack.io"
- name: bitnami  # etcd, https://github.com/bitnami/charts
  url: "https://charts.bitnami.com/bitnami"
- name: openebs  # https://github.com/openebs/charts
  url: "https://openebs.github.io/charts"
- name: hashicorp  # https://github.com/hashicorp/vault-helm
  url: "https://helm.releases.hashicorp.com"
- name: external-secrets  # https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
  url: "https://charts.external-secrets.io"

## ingresses
# ref: https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md#differences-between-nginxinckubernetes-ingress-and-kubernetesingress-nginx-ingress-controllers
- name: nginx  # src: https://github.com/nginxinc/kubernetes-ingress/tree/master/deployments/helm-chart
  url: "https://helm.nginx.com/edge"
# ref: https://kubernetes.github.io/ingress-nginx/user-guide/
- name: kubernetes-nginx  # src: https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: prometheus-community  # https://github.com/prometheus-community/helm-charts
  url: "https://prometheus-community.github.io/helm-charts"
- name: vmware-tanzu
  url: "https://vmware-tanzu.github.io/helm-charts"
- name: kedacore
  url: "https://kedacore.github.io/charts"

# curiosities
#
## LOL SSPL-LICENSED SOFTWARE, DO NOT TOUCH
#- name: elastic  # https://github.com/elastic/helm-charts
#  url: "https://helm.elastic.co"

- name: rancher
  url: "https://releases.rancher.com/server-charts/latest"

helmDefaults:
  wait: true
  timeout: {{ .Values.helmTimeout }}
  tillerless: false
  #skipDeps: true
  #createNamespace: true
  #cleanupOnFail: true

#bases: {}
#helmFiles:
#- path: postgres-operator-helmfile.yaml
#- path: rancher-helmfile.yaml

templates:
  openebs:
    values:
    - disabledComponent: &openebsLVP
        enabled: false
        replicas: 0
      openebsTag: &openebsTag
        imageTag: {{ .Values.versions.images.openebs }}
      openebsNdmTag: &openebsNdmTag
        imageTag: {{ .Values.versions.images.openebsNdm }}

releases:
- name: {{ .Values.releases.ingressController }}
  namespace: {{ .Values.namespaces.network }}
  chart: nginx/nginx-ingress
  #chart: kubernetes-nginx/ingress-nginx
  version: {{ .Values.versions.charts.nginx }}
  labels:
    purpose: ingress
  values:
  - controller:
      hostNetwork: false
      kind: daemonset
      service:
        type: NodePort
      enableCustomResources: false
      setAsDefaultIngress: true
      image:
        tag: {{ .Values.versions.images.nginx }}

{{- if ne .Values.k8sRuntime "k3d" }}
- name: {{ .Values.releases.openebs }}
  namespace: {{ .Values.namespaces.storage }}
  chart: openebs/openebs
  version: {{ .Values.versions.charts.openebs }}
  values:  # ref: https://openebs.github.io/charts/openebs-lite-helm-values.yaml
  - fullnameOverride: {{ .Values.releases.openebs | quote }}
    rbac:
      pspEnabled: true
    #image:  # hopefully a temporary state of affairs
    #  repository: docker.io/
    analytics:
      enabled: false
    release:
      version: {{ .Values.versions.images.openebs }}
    apiserver:  # not needed for just local PV
      <<: *openebsLVP
      <<: *openebsTag
    provisioner:  # not needed for just local PV
      <<: *openebsLVP
      <<: *openebsTag
    localprovisioner:
      enabled: true
      replicas: 3
      <<: *openebsTag
    snapshotOperator:  # not needed for just local PV
      <<: *openebsLVP
      controller:
        <<: *openebsTag
      provisioner:
        <<: *openebsTag
    webhook:  # not needed for just local PV
      <<: *openebsLVP
      <<: *openebsTag
    jiva:
      <<: *openebsTag
    cstor:
      pool:
        <<: *openebsTag
      poolMgmt:
        <<: *openebsTag
      target:
        <<: *openebsTag
      volumeMgmt:
        <<: *openebsTag
    helper:
      <<: *openebsTag
    policies:
      monitoring:
        <<: *openebsTag
    ndmOperator:
      enabled: false
      <<: *openebsNdmTag
    ndm:
      enabled: false
      <<: *openebsNdmTag
      filters:
        {{/* excludePaths: "/dev/sd,/dev/vd,fd0,sr0,/dev/ram,/dev/dm-,/dev/md,/dev/zram{{ if ne .Values.openebsOmitLoopDevs "," }}{{ .Values.openebsOmitLoopDevs }}{{ end }}" */}}
        includePaths: "/dev/loop"
  hooks:
  - events: ["postsync"]
    command: "/bin/sh"
    args:
    - "-xec"
    - |
      for i in $(kubectl get sc -o jsonpath='{.items[?(@.metadata.annotations.storageclass\.kubernetes\.io/is-default-class=="true")].metadata.name}'); do
        kubectl annotate sc ${i} storageclass.kubernetes.io/is-default-class-
      done
      kubectl apply -f- <<EOF
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      provisioner: openebs.io/local
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Delete
      metadata:
        name: openebs-hostpath
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
          openebs.io/cas-type: local
          cas.openebs.io/config: |
            #hostpath type will create a PV by
            # creating a sub-directory under the
            # BASEPATH provided below.
            - name: StorageType
              value: "hostpath"
            #Specify the location (directory) where
            # where PV(volume) data will be saved.
            # A sub-directory with pv-name will be
            # created. When the volume is deleted,
            # the PV sub-directory will be deleted.
            #Default value is /var/openebs/local
            - name: BasePath
              value: "/var/openebs/local/"
      #---
      #apiVersion: storage.k8s.io/v1
      #kind: StorageClass
      #provisioner: openebs.io/local
      #volumeBindingMode: WaitForFirstConsumer
      #reclaimPolicy: Delete
      #metadata:
      #  name: openebs-device
      #  annotations:
      #    openebs.io/cas-type: local
      #    cas.openebs.io/config: |
      #      #device type will create a PV by
      #      # issuing a BDC and will extract the path
      #      # values from the associated BD.
      #      - name: StorageType
      #        value: "device"
      EOF
{{- end }}

- name: {{ .Values.releases.certManager }}
  namespace: {{ .Values.namespaces.network }}
  chart: jetstack/cert-manager
  version: v{{ .Values.versions.images.certManager }}
  values:
  - installCRDs: true
  hooks:
  - events: ["postsync"]
    command: "/bin/sh"
    args:
    - "-xec"
    - |
{{- range (values .Values.namespaces) }}
      kubectl get ns {{ . }} || kubectl create ns {{ . }}
{{- end }}
      until kubectl -n {{ .Values.namespaces.network }} wait --for condition=ready pod -l app.kubernetes.io/instance=cert-manager,app.kubernetes.io/component=webhook; do sleep 1; done 2>/dev/null ||:
      until [ $(kubectl get validatingwebhookconfigurations cert-manager-webhook -o jsonpath='{.webhooks[*].clientConfig.caBundle}' | wc -c) -gt 1 ]; do sleep 1; done
      until [ $(kubectl get mutatingwebhookconfigurations cert-manager-webhook -o jsonpath='{.webhooks[*].clientConfig.caBundle}' | wc -c) -gt 1 ]; do sleep 1; done
      #until kubectl -n kube-system exec -ti $(kubectl -n kube-system get pod -l app=flannel -o jsonpath='{.items[0].metadata.name}' --sort-by '{.metadata.name}') -- wget https://cert-manager-webhook.{{ .Values.namespaces.network }}.svc &>/dev/null; do sleep 1; done
      kubectl apply -f- <<EOF
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned
        namespace: kube-system
      spec:
        selfSigned: {}
{{- range (values .Values.namespaces) }}
      ---
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: selfsigned-ca-tls
        namespace: {{ . }}
      spec:
        secretName: selfsigned-ca-tls
        isCA: true
        commonName: "{{ . }}.svc.cluster.local"
        dnsNames: ["{{ . }}.svc.cluster.local"]
        issuerRef:
          name: selfsigned
          kind: ClusterIssuer
      ---
      apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        name: selfsigned-ca
        namespace: {{ . }}
      spec:
        ca:
          secretName: selfsigned-ca-tls
{{- end }}
      ---
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: istio-root-ca-tls
        namespace: {{ $.Values.namespaces.network }}
      spec:
        secretName: istio-root-ca-tls
        isCA: true
        commonName: "Istio Root CA"
        issuerRef:
          name: selfsigned
          kind: ClusterIssuer
      ---
      apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        name: istio-root-ca
        namespace: {{ $.Values.namespaces.network }}
      spec:
        ca:
          secretName: {{ $.Values.istio.certs.rootCaSecret }}
{{- range (list "cluster0" "cluster1") }}
      ---
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: {{ . }}-istio-ca-tls
        namespace: {{ $.Values.namespaces.network }}
      spec:
        secretName: {{ . }}-istio-ca-tls
        isCA: true
        commonName: "Istio {{ . }} CA"
        dnsNames: ["istiod.{{ $.Values.namespaces.network }}.svc.cluster.local"]
        issuerRef:
          name: istio-root-ca
          kind: Issuer
{{- end }}
      EOF

- name: {{ .Values.releases.etcd }}
  namespace: {{ .Values.namespaces.storage }}
  chart: bitnami/etcd
  version: {{ .Values.versions.charts.etcd }}
{{- if ne .Values.k8sRuntime "k3d" }}
  needs:
  - {{ .Values.namespaces.storage }}/{{ .Values.releases.openebs }}
{{- end }}
  values:
  - replicaCount: {{ .Values.etcd.replicas }}
    image:
      tag: {{ .Values.versions.images.etcd }}
    #podManagementPolicy: OrderedReady
    autoCompactionMode: periodic
    autoCompactionRetention: 1
    extraEnvVars:
    - name: ETCD_QUOTA_BACKEND_BYTES
      value: "8589934592"
    auth:
      rbac:
        create: false
        allowNoneAuthentication: true
        enabled: false
        rootPassword: etcd

- name: {{ .Values.releases.vault }}
  namespace: {{ .Values.namespaces.storage }}
  chart: hashicorp/vault
  #version: {{ .Values.versions.charts.vault }}
  needs:
  - {{ .Values.namespaces.storage }}/{{ .Values.releases.etcd }}
  values:
  - injector:
      #metrics:
      #  enabled: true
      agentImage:
        tag: {{ .Values.versions.images.vault }}
    server:
      affinity: ""
      image:
        tag: {{ .Values.versions.images.vault }}
      auditStorage:
        enabled: true
      ha:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "etcd" {
            address = "http://{{ .Values.releases.etcd }}.{{ .Values.namespaces.storage }}.svc:2379"
            path = "vault/"
            ha_enabled = "true"
            etcd_api = "v3"
          }
          service_registration "kubernetes" {}
  hooks:
  - events: ["postsync"]
    command: "/bin/sh"
    args:
    - "-xec"
    - |
      until kubectl -n {{ .Values.namespaces.storage }} exec -i "{{ .Values.releases.vault }}-0" -- echo; do sleep 1; done 2>/dev/null ||:
      TMPFILE="$(mktemp)"
      until kubectl -n {{ .Values.namespaces.storage }} exec -i "{{ .Values.releases.vault }}-0" -- vault operator init >"${TMPFILE}"; do sleep 3; done

      for i in $(seq 0 2); do
        awk '/Unseal Key/ {print $NF}' "${TMPFILE}" | xargs -n1 -- kubectl -n {{ .Values.namespaces.storage }} exec -i "{{ .Values.releases.vault }}-${i}" -- vault operator unseal
      done

      kubectl apply -f- <<EOF
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: {{ .Values.externalSecrets.vaultTokenRef.namespace | quote }}
        name: {{ .Values.externalSecrets.vaultTokenRef.secretName | quote }}
      stringData:
        {{ .Values.externalSecrets.vaultTokenRef.key }}: "$(awk '/Initial Root Token/ {print $NF}' "${TMPFILE}")"
      EOF
      rm "${TMPFILE}"

- name: {{ .Values.releases.externalSecrets }}
  namespace: {{ .Values.namespaces.storage }}
  chart: external-secrets/external-secrets
  version: {{ .Values.versions.charts.externalSecrets }}
  needs:
  - {{ .Values.namespaces.storage }}/{{ .Values.releases.vault }}
  values:
  - image:
      tag: "v{{ .Values.versions.images.externalSecrets }}"
  hooks:
  - events: ["postsync"]
    command: "/bin/sh"
    args:
    - "-xec"
    - |
      kubectl apply -f- <<EOF
      # https://external-secrets.io/spec/
      apiVersion: external-secrets.io/v1alpha1
      kind: ClusterSecretStore
      metadata:
        name: vault-backend
      spec:
        provider:
          vault:
            server: "http://{{ .Values.releases.vault }}.{{ .Values.namespaces.storage }}.svc:8200"
            path: "secret"
            version: "v2"
            auth:  # https://external-secrets.io/provider-hashicorp-vault/#kubernetes-authentication is probably a better idea
              tokenSecretRef:
                name: {{ .Values.externalSecrets.vaultTokenRef.secretName | quote }}
                namespace: {{ .Values.externalSecrets.vaultTokenRef.namespace | quote }}
                key: {{ .Values.externalSecrets.vaultTokenRef.key | quote }}
      EOF
