bases:
- "{{ requiredEnv "MYDIR" }}/helmfile/envs.yaml"
---
repositories:
- name: grafana  # https://github.com/grafana/helm-charts
  url: "https://grafana.github.io/helm-charts"
{{- if semverCompare "<1.6" .Values.versions.images.istio }}
- name: istio  # https://github.com/istio/istio/tree/master/manifests/charts
  url: "https://storage.googleapis.com/istio-release/releases/{{ .Values.versions.images.istio }}/charts"
{{- end }}
- name: jaegertracing  # src: https://github.com/jaegertracing/helm-charts
  url: "https://jaegertracing.github.io/helm-charts"
- name: kiali  # https://github.com/kiali/helm-charts
  url: "https://kiali.org/helm-charts"
- name: traefik  # https://github.com/traefik/traefik-helm-chart
  url: "https://traefik.github.io/charts"

templates:
  istio:
    values:
    - global: &istioGlobal
        hub: docker.io/istio
        tag: {{ .Values.versions.images.istio }}
        istioNamespace: {{ .Values.namespaces.network }}
        telemetryNamespace: {{ .Values.namespaces.network }}
        prometheusNamespace: {{ .Values.namespaces.network }}
        policyNamespace: {{ .Values.namespaces.network }}
        configRootNamespace: {{ .Values.namespaces.network }}
{{- if semverCompare "<1.9" .Values.versions.images.istio }}
        meshExpansion:
          enabled: true
{{- end }}
{{- if .Values.istio.multiCluster }}
        externalIstiod: true
        meshID: "{{ .Values.istio.meshID }}"
        multiCluster:
          #enabled: true
          clusterName: "{{ .Values.istio.cluster }}"
        network: "{{ .Values.istio.network }}"
{{- end }}
      control: &istioControl
        disablePolicyChecks: false
        mtls:
          enabled: true
        outboundTrafficPolicy:
          mode: ALLOW_ANY
        proxy:
          accessLogFile: /dev/stdout
        sds:
          enabled: true
          udsPath: "unix:/var/run/sds/uds_path"
      gateways:
        istio-ingressgateway: &istioIngress
          type: NodePort
        istio-egressgateway: &istioEgress
          type: NodePort
    - &istioOldCertManager
      certmanager:
        enabled: true
    - &istioKiali
      kiali:
        enabled: true
        createDemoSecret: true
        dashboard:
          grafanaURL: "http://grafana.{{ .Values.namespaces.network }}.svc:3000"
          jaegerURL: "http://{{ .Values.releases.jaegerOperator }}-jaeger-query.{{ .Values.namespaces.network }}.svc:16686"
    - &istioMixer
      mixer:
        # istio-policy
        policy:
          enabled: true
        # istio-telemetry/mixer-telemetry
        adapters:
          stdio:
            enabled: true
        telemetry:
          enabled: true

releases:
# network components
- name: {{ .Values.releases.jaegerOperator }}
  namespace: {{ .Values.namespaces.network }}
  chart: jaegertracing/jaeger-operator
  installed: {{ .Values.enables.network }}
  version: {{ .Values.versions.charts.jaegerOperator }}
  values:
  - fullnameOverride: {{ .Values.releases.jaegerOperator | quote }}
    image:
      tag: {{ .Values.versions.images.jaeger }}
    jaeger:
      create: true
      spec:  # https://www.jaegertracing.io/docs/1.16/operator/
        strategy: allInOne
        ingress:
          enabled: false
    # https://github.com/jaegertracing/jaeger-operator/issues/791
    rbac:
      clusterRole: true
{{- if semverCompare "<1.6" .Values.versions.images.istio }}
- name: {{ .Values.releases.istio.init }}
  namespace: {{ .Values.namespaces.network }}
  chart: istio/istio-init
  installed: {{ .Values.enables.network }}
  values:
  - *istioOldCertManager

- name: {{ .Values.releases.istio.old }}
  namespace: {{ .Values.namespaces.network }}
  chart: istio/istio
  installed: {{ .Values.enables.network }}
  needs:
  - {{ .Values.namespaces.network }}/{{ .Values.releases.istio.init }}
  - {{ .Values.namespaces.network }}/{{ .Values.releases.jaegerOperator }}
  {{- if .Values.enables.network }}
  hooks:
  - events: ["presync"]
    command: "/bin/sh"
    args: ["-xec", "kubectl -n {{ .Values.namespaces.network }} wait --for condition=complete --timeout {{ .Values.helmTimeout }}s job --all"]
  {{- end }}
  values:
  - fullnameOverride: {{ .Values.releases.istio.old | quote }}
    global:
      <<: *istioGlobal
      <<: *istioControl
    <<: *istioOldCertManager
    <<: *istioKiali
    <<: *istioMixer
    gateways:
      istio-ingressgateway:
        <<: *istioIngress
        sds:
          enabled: true
      istio-egressgateway:
        <<: *istioEgress
        enabled: true
    # === removed in 1.6 ===
    nodeagent:  # part of istio-proxy
      enabled: true
      env:
        CA_PROVIDER: Citadel
        CA_ADDR: "istio-citadel.{{ .Values.namespaces.network }}.svc:8060"
        VALID_TOKEN: true
    security:  # citadel is part of istio-pilot
      citadelHealthCheck: true
    sidecarInjectorWebhook:  # part of control plane (istiod)
      enabled: true
{{- else }}
- name: {{ .Values.releases.istio.base }}
  namespace: {{ .Values.namespaces.network }}
  chart: {{ .Values.chartBases.istio }}/charts/base
  installed: {{ .Values.enables.network }}
  {{- if .Values.istio.multiCluster }}
  hooks:
  - events: ["postsync"]
    command: "/bin/sh"
    args:  # add our own remote-secret to our stash
    - "-xec"
    - |
      CONFIG_CLUSTER=$(kubectl config view -o jsonpath="{.contexts[?(@.name==\"$(kubectl config view -o jsonpath='{.current-context}')\")].context.cluster}")
      MYTEMP="$(mktemp)"
      cat <<EOF >"${MYTEMP}"
      apiVersion: v1
      kind: Secret
      metadata:
        name: istio-remote-secret-{{ .Values.istio.cluster }}
        namespace: {{ .Values.namespaces.network }}
        labels:
          istio/multiCluster: "true"
        annotations:
          networking.istio.io/cluster: {{ .Values.istio.cluster }}
      stringData:
        {{ .Values.istio.cluster }}: |
          apiVersion: v1
          kind: Config
          preferences: {}
          clusters:
          - name: {{ .Values.istio.cluster }}
            cluster:
              certificate-authority-data: $(kubectl -n {{ .Values.namespaces.network }} get secret/$(kubectl -n {{ .Values.namespaces.network }} get sa/istio-reader-service-account -o jsonpath='{.secrets[0].name}') -o jsonpath='{.data.ca\.crt}')
              server: https://$(kubectl get node -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'):6443
              #server: $(kubectl config view -o jsonpath="{.clusters[?(@.name==\"${CONFIG_CLUSTER}\")].cluster.server}")
          contexts:
          - name: {{ .Values.istio.cluster }}
            context:
              cluster: {{ .Values.istio.cluster }}
              user: {{ .Values.istio.cluster }}
          current-context: {{ .Values.istio.cluster }}
          users:
          - name: {{ .Values.istio.cluster }}
            user:
              token: $(kubectl -n {{ .Values.namespaces.network }} get secret/$(kubectl -n {{ .Values.namespaces.network }} get sa/istio-reader-service-account -o jsonpath='{.secrets[0].name}') -o jsonpath='{.data.token}' | base64 -dw0)
      EOF
      kubectl create -f "${MYTEMP}" || kubectl replace -f "${MYTEMP}"; rm "${MYTEMP}"
  {{- end }}
  values:
  {{- if semverCompare "<1.9" .Values.versions.images.istio }}
  - {{ .Values.chartBases.istio }}/charts/global.yaml
  {{- end }}
  - global:
      <<: *istioGlobal
    #base:  # helm2
    #  enableCRDTemplates: true

{{- $istioCaClusterKubeCfg := "" }}
{{- if eq .Values.k8sRuntime "k3d" }}
  {{- $istioCaClusterKubeCfg = printf "$(k3d kubeconfig write %s)" (default "cluster0" (env "ISTIO_CA_CLUSTER")) }}
{{- else if eq .Values.k8sRuntime "kubedee" }}
  {{- $istioCaClusterKubeCfg = printf "${HOME}/.local/share/kubedee/clusters/%s/kubeconfig/admin.kubeconfig" (default "cluster0" (env "ISTIO_CA_CLUSTER")) }}
{{- end }}
- name: {{ .Values.releases.istio.control }}
  namespace: {{ .Values.namespaces.network }}
  chart: {{ .Values.chartBases.istio }}/charts/istio-control/istio-discovery
  installed: {{ .Values.enables.network }}
  needs:
  - {{ .Values.namespaces.network }}/{{ .Values.releases.istio.base }}
  {{- if .Values.istio.multiCluster }}
  hooks:
  - events: ["presync"]
    command: "/bin/sh"
    args:
    - "-xec"
    - |
      kubectl label ns {{ .Values.namespaces.network }} topology.istio.io/network={{ .Values.istio.network }}
      kubectl apply -f- <<EOF
      apiVersion: v1
      kind: Secret
      metadata:
        name: cacerts
        namespace: {{ .Values.namespaces.network }}
      type: Opaque
      data:
        ca-cert.pem: $(KUBECONFIG="{{ $istioCaClusterKubeCfg }}" kubectl -n {{ .Values.namespaces.network }} get secret/{{ .Values.istio.certs.clusterSecret }} -o jsonpath='{.data.tls\.crt}')
        ca-key.pem: $(KUBECONFIG="{{ $istioCaClusterKubeCfg }}" kubectl -n {{ .Values.namespaces.network }} get secret/{{ .Values.istio.certs.clusterSecret }} -o jsonpath='{.data.tls\.key}')
        cert-chain.pem: $(sh -ec "KUBECONFIG={{ $istioCaClusterKubeCfg }} kubectl -n {{ .Values.namespaces.network }} get secret/{{ .Values.istio.certs.clusterSecret }} -o jsonpath='{.data.tls\.crt}' | base64 -dw0; KUBECONFIG={{ $istioCaClusterKubeCfg }} kubectl -n {{ .Values.namespaces.network }} get secret/{{ .Values.istio.certs.rootCaSecret }} -o jsonpath='{.data.tls\.crt}' | base64 -dw0" | base64 -w0)
        root-cert.pem: $(KUBECONFIG="{{ $istioCaClusterKubeCfg }}" kubectl -n {{ .Values.namespaces.network }} get secret/{{ .Values.istio.certs.rootCaSecret }} -o jsonpath='{.data.tls\.crt}')
      EOF
  {{- end }}
  values:
  {{- if semverCompare "<1.9" .Values.versions.images.istio }}
  - {{ .Values.chartBases.istio }}/charts/global.yaml
  {{- end }}
  - global:
      <<: *istioGlobal
      <<: *istioControl
    meshConfig:
      rootNamespace: {{ .Values.namespaces.network }}

- name: {{ .Values.releases.istio.gateway.egress }}
  namespace: {{ .Values.namespaces.network }}
  chart: {{ .Values.chartBases.istio }}/charts/gateways/istio-egress
  installed: {{ .Values.enables.network }}
  needs:
  - {{ .Values.namespaces.network }}/{{ .Values.releases.istio.control }}
  values:
  {{- if semverCompare "<1.9" .Values.versions.images.istio }}
  - {{ .Values.chartBases.istio }}/charts/global.yaml
  {{- end }}
  - global:
      <<: *istioGlobal
    gateways:
      istio-egressgateway:
        <<: *istioEgress

- name: {{ .Values.releases.istio.gateway.ingress }}
  namespace: {{ .Values.namespaces.network }}
  chart: {{ .Values.chartBases.istio }}/charts/gateways/istio-ingress
  installed: {{ .Values.enables.network }}
  needs:
  - {{ .Values.namespaces.network }}/{{ .Values.releases.istio.control }}
  hooks:
  - events: ["postsync"]
    command: "/bin/sh"
    args:
    - "-xec"
    - |
      kubectl apply -f- <<EOF
      apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      metadata:
        name: istiod-gateway
        namespace: {{ .Values.namespaces.network }}
      spec:
        selector:
          istio: eastwestgateway
        servers:
        - port:
            name: tls-istiod
            number: 15012
            protocol: tls
          tls:
            mode: PASSTHROUGH
          hosts:
          - "*"
        - port:
            name: tls-istiodwebhook
            number: 15017
            protocol: tls
          tls:
            mode: PASSTHROUGH
          hosts:
          - "*"
      ---
      apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      metadata:
        name: istiod-vs
        namespace: {{ .Values.namespaces.network }}
      spec:
        hosts:
        - "*"
        gateways:
        - istiod-gateway
        tls:
        - match:
          - port: 15012
            sniHosts:
            - "*"
          route:
          - destination:
              host: istiod.{{ .Values.namespaces.network }}.svc.cluster.local
              port:
                number: 15012
        - match:
          - port: 15017
            sniHosts:
            - "*"
          route:
          - destination:
              host: istiod.{{ .Values.namespaces.network }}.svc.cluster.local
              port:
                number: 443
      ---
      apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      metadata:
        name: cross-network-gateway
        namespace: {{ .Values.namespaces.network }}
      spec:
        selector:
          {{ default (dict) .Values.istio.gateway.labels | toYaml | nindent 10 }}
        servers:
        - port:
            number: 15443
            name: tls
            protocol: TLS
          tls:
            mode: AUTO_PASSTHROUGH
          hosts:
          - "*.local"
      EOF
      # only because we're using NodePort services
      kubectl -n {{ .Values.namespaces.network }} patch svc/istio-eastwestgateway -p "{\"spec\":{\"externalIPs\":[\"$(kubectl get node -l node-role.kubernetes.io/master -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')\"]}}"
  values:
  {{- if semverCompare "<1.9" .Values.versions.images.istio }}
  - {{ .Values.chartBases.istio }}/charts/global.yaml
  {{- end }}
  - global:
      <<: *istioGlobal
    gateways:
      istio-ingressgateway:
        <<: *istioIngress
        name: istio-eastwestgateway
        labels:
          app: istio-eastwestgateway
          topology.istio.io/network: {{ .Values.istio.network }}
          {{ default (dict) .Values.istio.gateway.labels | toYaml | nindent 10 }}
        env:
          ISTIO_META_ROUTER_MODE: "sni-dnat"
          ISTIO_META_REQUESTED_NETWORK_VIEW: {{ .Values.istio.network }}
        ports:
        - name: status-port
          port: 15021
          targetPort: 15021
        - name: tls
          port: 15443
          targetPort: 15443
        - name: tls-istiod
          port: 15012
          targetPort: 15012
        - name: tls-webhook
          port: 15017
          targetPort: 15017
  {{- if semverCompare "<1.8" .Values.versions.images.istio }}
- name: {{ .Values.releases.istio.policy }}
  namespace: {{ .Values.namespaces.network }}
  chart: {{ .Values.chartBases.istio }}/charts/istio-policy
  installed: {{ .Values.enables.network }}
  needs:
  - {{ .Values.namespaces.network }}/{{ .Values.releases.istio.control }}
  values:
    {{- if semverCompare "<1.9" .Values.versions.images.istio }}
  - {{ .Values.chartBases.istio }}/charts/global.yaml
    {{- end }}
  - global:
      <<: *istioGlobal
    <<: *istioMixer
  {{- end }}

- name: {{ .Values.releases.istio.telemetry.grafana }}
  namespace: {{ .Values.namespaces.network }}
  installed: {{ .Values.enables.network }}
  {{- if semverCompare "<1.8" .Values.versions.images.istio }}
  chart: {{ .Values.chartBases.istio }}/charts/istio-telemetry/grafana
  needs:
  - {{ .Values.namespaces.network }}/{{ .Values.releases.istio.control }}
  values:
    {{- if semverCompare "<1.9" .Values.versions.images.istio }}
  - {{ .Values.chartBases.istio }}/charts/global.yaml
    {{- end }}
  - global:
      <<: *istioGlobal
  {{- else }}
  chart: grafana/grafana
  version: {{ .Values.versions.charts.grafana }}
  values:
  - {{ .Values.chartBases.istio }}/addons/values-grafana.yaml
  - image:
      tag: {{ .Values.versions.images.grafana }}
    {{- if .Values.enables.network }}
  hooks:
  - events: ["presync"]
    command: "/bin/sh"
    args:
    - "-xec"
    - |
      kubectl get ns {{ .Values.namespaces.network }} || kubectl create ns {{ .Values.namespaces.network }}
      MYTMP="$(mktemp)"
      kubectl create configmap -n {{ .Values.namespaces.network }} istio-grafana-dashboards \
        --from-file=pilot-dashboard.json="{{ .Values.chartBases.istio }}/addons/dashboards/pilot-dashboard.json" \
        --from-file=istio-performance-dashboard.json="{{ .Values.chartBases.istio }}/addons/dashboards/istio-performance-dashboard.json" -o yaml --dry-run=client >"${MYTMP}"; kubectl create -f "${MYTMP}" || kubectl replace -f "${MYTMP}"
      kubectl create configmap -n {{ .Values.namespaces.network }} istio-services-grafana-dashboards \
        --from-file=istio-workload-dashboard.json="{{ .Values.chartBases.istio }}/addons/dashboards/istio-workload-dashboard.json" \
        --from-file=istio-service-dashboard.json="{{ .Values.chartBases.istio }}/addons/dashboards/istio-service-dashboard.json" \
        --from-file=istio-mesh-dashboard.json="{{ .Values.chartBases.istio }}/addons/dashboards/istio-mesh-dashboard.json" -o yaml --dry-run=client >"${MYTMP}"; kubectl create -f "${MYTMP}" || kubectl replace -f "${MYTMP}"
      rm "${MYTMP}"
    {{- end }}
  {{- end }}

- name: {{ .Values.releases.istio.telemetry.kiali }}
  namespace: {{ .Values.namespaces.network }}
  installed: {{ .Values.enables.network }}
  {{- if semverCompare "<1.8" .Values.versions.images.istio }}
  chart: {{ .Values.chartBases.istio }}/charts/istio-telemetry/kiali
  needs:
  - {{ .Values.namespaces.network }}/{{ .Values.releases.istio.control }}
  values:
    {{- if semverCompare "<1.9" .Values.versions.images.istio }}
  - {{ .Values.chartBases.istio }}/charts/global.yaml
    {{- end }}
  - global:
      <<: *istioGlobal
    <<: *istioKiali
  {{- else }}
  chart: "{{ requiredEnv "MYDIR" }}/charts/kiali/kiali-server"
  values:
  - {{ .Values.chartBases.istio }}/addons/values-kiali.yaml
  - deployment:
      image_version: "v{{ .Values.versions.images.kiali }}"
      version_label: "v{{ .Values.versions.images.kiali }}"
  {{- end }}
{{- end }}

# https://github.com/coreos/prometheus-operator/issues/2502
# https://github.com/istio/installer/pull/71
- name: {{ .Values.releases.istio.telemetry.prometheusOperator }}
  namespace: {{ .Values.namespaces.network }}
  installed: {{ and .Values.enables.network .Values.enables.monitoring }}
{{- if semverCompare "<1.8" .Values.versions.images.istio }}
  chart: {{ .Values.chartBases.istio }}/charts/istio-telemetry/prometheusOperator
  needs:
  - {{ .Values.namespaces.monitoring }}/{{ .Values.releases.kubePromStack }}
  {{- if semverCompare "<1.6" .Values.versions.images.istio }}
  - {{ .Values.namespaces.network }}/{{ .Values.releases.istio.old }}
  {{- else }}
  - {{ .Values.namespaces.network }}/{{ .Values.releases.istio.control }}
  {{- end }}
  values:
  {{- if semverCompare "<1.9" .Values.versions.images.istio }}
  - {{ .Values.chartBases.istio }}/charts/global.yaml
  {{- end }}
  - global:
      <<: *istioGlobal
{{- else }}
  chart: prometheus-community/prometheus
  version: {{ .Values.versions.charts.prometheus }}
  values:
  - {{ .Values.chartBases.istio }}/addons/values-prometheus.yaml
{{- end }}
