bases:
- "{{ requiredEnv "MYDIR" }}/helmfile/envs.yaml"
---
helmDefaults:
  wait: true
  timeout: {{ .Values.helmTimeout }}
  tillerless: false
  #skipDeps: true
  #createNamespace: true
  #cleanupOnFail: true

helmfiles:
- "{{ requiredEnv "MYDIR" }}/helmfile/common.yaml"
- "{{ requiredEnv "MYDIR" }}/helmfile/storage.yaml"
- "{{ requiredEnv "MYDIR" }}/helmfile/network.yaml"
- "{{ requiredEnv "MYDIR" }}/helmfile/monitoring.yaml"
- "{{ requiredEnv "MYDIR" }}/helmfile/development.yaml"
#- "{{ requiredEnv "MYDIR" }}/helmfile/streaming.yaml"
