bases:
- "{{ requiredEnv "MYDIR" }}/helmfile/envs.yaml"
---
helmDefaults:
  wait: true
  timeout: {{ .Values.helmTimeout }}
  tillerless: false
  #skipDeps: true
  #createNamespace: true
  #cleanupOnFail: true

helmfiles:
- "{{ requiredEnv "MYDIR" }}/helmfile/common.yaml"
- "{{ requiredEnv "MYDIR" }}/helmfile/rook.yaml"
- "{{ requiredEnv "MYDIR" }}/helmfile/infra.yaml"
- "{{ requiredEnv "MYDIR" }}/helmfile/openstack.yaml"
