---
apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: runc  # The name the RuntimeClass will be referenced by
handler: runc  # The name of the corresponding CRI configuration
---
apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: kata-qemu
handler: kata-qemu
---
apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: kata-fc
handler: kata-fc
---
apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: kata-clh
handler: kata-clh
